SET
    search_path TO ezecream_05;

-- cleans the table and resets the autogenerated pk value
TRUNCATE TABLE product RESTART IDENTITY CASCADE;

INSERT INTO
    product (name, price)
VALUES
    ('blåbärsmagi', 35),
    ('lakritsdrömmar', 40),
    ('lichipichi', 30);

SELECT
    *
FROM
    product;