SET
    search_path TO ezecream_05;

-- cleans the table and resets the autogenerated pk value
TRUNCATE TABLE product RESTART IDENTITY CASCADE;

INSERT INTO
    Product (product_id,name, price)
VALUES
    (1,'blåbärsmagi', 35),
    (2,'lakritsdrömmar', 40),
    (3,'lichipichi', 30);

SELECT
    *
FROM
    ezecream_05.product;